# Security / JWT
jwt.secret=9a674758d97e9e02c65a4c6a6616e4dae07ef0581458e0a8ad679e9a4f4c5a0a
jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
